/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafiskinterface;

/**
 *
 * @author Simon
 */

import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.*;
import databas.DBClass;
import javax.swing.JOptionPane;
import java.awt.CardLayout;

public class AccountManagement extends javax.swing.JFrame {

    
    private InfDB sqlMethods;
    private DBClass dataBase;
    /**
     * Creates new form AccountManagement
     */
    public AccountManagement() {
        dataBase = new DBClass();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        btn_AccountManagement_MainPanel_LaggTillKonto = new javax.swing.JButton();
        btn_AccountManagement_MainPanel_AndraKonto = new javax.swing.JButton();
        btn_AccountManagement_MainPanel_TaBortKonto = new javax.swing.JButton();
        btn_AccountManagement_MainPanel_Loggaut = new javax.swing.JButton();
        btn_AccountManagement_MainPanel_Avsluta = new javax.swing.JButton();
        CardPanelHolder = new javax.swing.JPanel();
        LaggTillKonto = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        lbl_AccountManagement_LaggTillKonto_name = new javax.swing.JLabel();
        tf_AccountManagement_LaggTillKonto_Name = new javax.swing.JTextField();
        lbl_AccountManagement_LaggTillKonto_username = new javax.swing.JLabel();
        tf_AccountManagement_LaggTillKonto_Username = new javax.swing.JTextField();
        lbl_AccountManagement_LaggTillKonto_Password = new javax.swing.JLabel();
        tf_AccountManagement_LaggTillKonto_Password = new javax.swing.JPasswordField();
        lbl_AccountManagement_LaggTillKonto_RepeatPassword = new javax.swing.JLabel();
        tf_Accountmanagement_LaggTillKonto_ChangePassword = new javax.swing.JPasswordField();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        btn_AccountManagement_LaggTillKonto_save = new javax.swing.JButton();
        AndraKonto = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPasswordField5 = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        jPasswordField6 = new javax.swing.JPasswordField();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        cb_AccountManagement_MainPanel_AndraKonto_AccountChooser = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        TaBortKonto = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jPasswordField9 = new javax.swing.JPasswordField();
        jLabel26 = new javax.swing.JLabel();
        jPasswordField10 = new javax.swing.JPasswordField();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jButton4 = new javax.swing.JButton();
        cb_AccountManagement_MainPanel_AndraKonto_AccountChooser1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(204, 204, 204));

        btn_AccountManagement_MainPanel_LaggTillKonto.setText("Lägg till konto");
        btn_AccountManagement_MainPanel_LaggTillKonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AccountManagement_MainPanel_LaggTillKontoActionPerformed(evt);
            }
        });

        btn_AccountManagement_MainPanel_AndraKonto.setText("Ändra konto");
        btn_AccountManagement_MainPanel_AndraKonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AccountManagement_MainPanel_AndraKontoActionPerformed(evt);
            }
        });

        btn_AccountManagement_MainPanel_TaBortKonto.setText("Ta bort konto");
        btn_AccountManagement_MainPanel_TaBortKonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AccountManagement_MainPanel_TaBortKontoActionPerformed(evt);
            }
        });

        btn_AccountManagement_MainPanel_Loggaut.setText("Logga ut");
        btn_AccountManagement_MainPanel_Loggaut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AccountManagement_MainPanel_LoggautActionPerformed(evt);
            }
        });

        btn_AccountManagement_MainPanel_Avsluta.setText("Avsluta");
        btn_AccountManagement_MainPanel_Avsluta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AccountManagement_MainPanel_AvslutaActionPerformed(evt);
            }
        });

        CardPanelHolder.setBackground(new java.awt.Color(153, 153, 153));
        CardPanelHolder.setLayout(new java.awt.CardLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Lägg till konto");
        jLabel17.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        lbl_AccountManagement_LaggTillKonto_name.setText("Namn");

        lbl_AccountManagement_LaggTillKonto_username.setText("Användarnamn");

        lbl_AccountManagement_LaggTillKonto_Password.setText("Lösenord");

        tf_AccountManagement_LaggTillKonto_Password.setName(""); // NOI18N

        lbl_AccountManagement_LaggTillKonto_RepeatPassword.setText("Upprepa lösenord");

        tf_Accountmanagement_LaggTillKonto_ChangePassword.setName(""); // NOI18N

        jCheckBox7.setText("Forskning");

        jCheckBox8.setText("Utbildning");

        btn_AccountManagement_LaggTillKonto_save.setText("Spara");
        btn_AccountManagement_LaggTillKonto_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AccountManagement_LaggTillKonto_saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LaggTillKontoLayout = new javax.swing.GroupLayout(LaggTillKonto);
        LaggTillKonto.setLayout(LaggTillKontoLayout);
        LaggTillKontoLayout.setHorizontalGroup(
            LaggTillKontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LaggTillKontoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LaggTillKontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_AccountManagement_LaggTillKonto_Name, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_AccountManagement_LaggTillKonto_Username)
                    .addComponent(tf_AccountManagement_LaggTillKonto_Password)
                    .addComponent(tf_Accountmanagement_LaggTillKonto_ChangePassword)
                    .addGroup(LaggTillKontoLayout.createSequentialGroup()
                        .addComponent(jCheckBox8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addComponent(btn_AccountManagement_LaggTillKonto_save))
                    .addGroup(LaggTillKontoLayout.createSequentialGroup()
                        .addGroup(LaggTillKontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(lbl_AccountManagement_LaggTillKonto_username)
                            .addComponent(lbl_AccountManagement_LaggTillKonto_Password)
                            .addComponent(lbl_AccountManagement_LaggTillKonto_RepeatPassword)
                            .addComponent(lbl_AccountManagement_LaggTillKonto_name)
                            .addComponent(jCheckBox7))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        LaggTillKontoLayout.setVerticalGroup(
            LaggTillKontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LaggTillKontoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_AccountManagement_LaggTillKonto_name, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_AccountManagement_LaggTillKonto_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lbl_AccountManagement_LaggTillKonto_username)
                .addGap(2, 2, 2)
                .addComponent(tf_AccountManagement_LaggTillKonto_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_AccountManagement_LaggTillKonto_Password)
                .addGap(3, 3, 3)
                .addComponent(tf_AccountManagement_LaggTillKonto_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_AccountManagement_LaggTillKonto_RepeatPassword)
                .addGap(1, 1, 1)
                .addComponent(tf_Accountmanagement_LaggTillKonto_ChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LaggTillKontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox8)
                    .addComponent(btn_AccountManagement_LaggTillKonto_save))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CardPanelHolder.add(LaggTillKonto, "card1");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Ändra konto");
        jLabel12.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel13.setText("Namn");

        jLabel14.setText("Användarnamn");

        jLabel15.setText("Lösenord");

        jPasswordField5.setName(""); // NOI18N

        jLabel16.setText("Upprepa lösenord");

        jPasswordField6.setName(""); // NOI18N

        jCheckBox5.setText("Forskning");

        jCheckBox6.setText("Utbildning");

        jButton3.setText("Spara");

        cb_AccountManagement_MainPanel_AndraKonto_AccountChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setText("Välj");

        javax.swing.GroupLayout AndraKontoLayout = new javax.swing.GroupLayout(AndraKonto);
        AndraKonto.setLayout(AndraKontoLayout);
        AndraKontoLayout.setHorizontalGroup(
            AndraKontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AndraKontoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AndraKontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField6)
                    .addComponent(jPasswordField5)
                    .addComponent(jPasswordField6)
                    .addGroup(AndraKontoLayout.createSequentialGroup()
                        .addComponent(jCheckBox6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(AndraKontoLayout.createSequentialGroup()
                        .addGroup(AndraKontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel13)
                            .addComponent(jCheckBox5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AndraKontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_AccountManagement_MainPanel_AndraKonto_AccountChooser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(AndraKontoLayout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        AndraKontoLayout.setVerticalGroup(
            AndraKontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AndraKontoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AndraKontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_AccountManagement_MainPanel_AndraKonto_AccountChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AndraKontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel14)
                .addGap(2, 2, 2)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(3, 3, 3)
                .addComponent(jPasswordField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(1, 1, 1)
                .addComponent(jPasswordField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AndraKontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox6)
                    .addComponent(jButton3))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        CardPanelHolder.add(AndraKonto, "card2");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Ta bort konto");
        jLabel22.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel23.setText("Namn");

        jTextField9.setEditable(false);

        jLabel24.setText("Användarnamn");

        jTextField10.setEditable(false);

        jLabel25.setText("Lösenord");

        jPasswordField9.setEditable(false);
        jPasswordField9.setName(""); // NOI18N

        jLabel26.setText("Upprepa lösenord");

        jPasswordField10.setEditable(false);
        jPasswordField10.setName(""); // NOI18N

        jCheckBox9.setText("Forskning");
        jCheckBox9.setEnabled(false);

        jCheckBox10.setText("Utbildning");
        jCheckBox10.setEnabled(false);

        jButton4.setText("Välj");

        cb_AccountManagement_MainPanel_AndraKonto_AccountChooser1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Ta bort konto");

        javax.swing.GroupLayout TaBortKontoLayout = new javax.swing.GroupLayout(TaBortKonto);
        TaBortKonto.setLayout(TaBortKontoLayout);
        TaBortKontoLayout.setHorizontalGroup(
            TaBortKontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaBortKontoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(TaBortKontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(cb_AccountManagement_MainPanel_AndraKonto_AccountChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaBortKontoLayout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(TaBortKontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TaBortKontoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(TaBortKontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField10)
                        .addComponent(jPasswordField9)
                        .addComponent(jPasswordField10)
                        .addGroup(TaBortKontoLayout.createSequentialGroup()
                            .addComponent(jCheckBox10)
                            .addGap(162, 162, 162))
                        .addGroup(TaBortKontoLayout.createSequentialGroup()
                            .addGroup(TaBortKontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel22)
                                .addComponent(jLabel24)
                                .addComponent(jLabel25)
                                .addComponent(jLabel26)
                                .addComponent(jLabel23)
                                .addComponent(jCheckBox9))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        TaBortKontoLayout.setVerticalGroup(
            TaBortKontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaBortKontoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb_AccountManagement_MainPanel_AndraKonto_AccountChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(TaBortKontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TaBortKontoLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel22)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(4, 4, 4)
                    .addComponent(jLabel24)
                    .addGap(2, 2, 2)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel25)
                    .addGap(3, 3, 3)
                    .addComponent(jPasswordField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel26)
                    .addGap(1, 1, 1)
                    .addComponent(jPasswordField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jCheckBox9)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBox10)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );

        CardPanelHolder.add(TaBortKonto, "card3");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CardPanelHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_AccountManagement_MainPanel_Avsluta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_AccountManagement_MainPanel_Loggaut, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_AccountManagement_MainPanel_AndraKonto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_AccountManagement_MainPanel_LaggTillKonto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(btn_AccountManagement_MainPanel_TaBortKonto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CardPanelHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(btn_AccountManagement_MainPanel_LaggTillKonto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_AccountManagement_MainPanel_AndraKonto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_AccountManagement_MainPanel_TaBortKonto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_AccountManagement_MainPanel_Loggaut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_AccountManagement_MainPanel_Avsluta)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Avslutar programmet.
    private void btn_AccountManagement_MainPanel_AvslutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AccountManagement_MainPanel_AvslutaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_AccountManagement_MainPanel_AvslutaActionPerformed

    private void btn_AccountManagement_MainPanel_LoggautActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AccountManagement_MainPanel_LoggautActionPerformed
        
        GrafikHelper.DisposeFrame();
        GrafikHelper.InitieraLogIn();
    }//GEN-LAST:event_btn_AccountManagement_MainPanel_LoggautActionPerformed

    private void btn_AccountManagement_MainPanel_LaggTillKontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AccountManagement_MainPanel_LaggTillKontoActionPerformed
        CardLayout card = (CardLayout)CardPanelHolder.getLayout();
        card.show(CardPanelHolder, "card1");
    }//GEN-LAST:event_btn_AccountManagement_MainPanel_LaggTillKontoActionPerformed

    private void btn_AccountManagement_MainPanel_AndraKontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AccountManagement_MainPanel_AndraKontoActionPerformed
        CardLayout card = (CardLayout)CardPanelHolder.getLayout();
        card.show(CardPanelHolder, "card2");
    }//GEN-LAST:event_btn_AccountManagement_MainPanel_AndraKontoActionPerformed

    private void btn_AccountManagement_MainPanel_TaBortKontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AccountManagement_MainPanel_TaBortKontoActionPerformed
        CardLayout card = (CardLayout)CardPanelHolder.getLayout();
        card.show(CardPanelHolder, "card3");
    }//GEN-LAST:event_btn_AccountManagement_MainPanel_TaBortKontoActionPerformed

    private void btn_AccountManagement_LaggTillKonto_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AccountManagement_LaggTillKonto_saveActionPerformed
        String GUIName = tf_AccountManagement_LaggTillKonto_Name.getText();
        String GUIUsername = tf_AccountManagement_LaggTillKonto_Username.getText();
        String GUIPassword = String.valueOf(tf_AccountManagement_LaggTillKonto_Password.getPassword());
        String GUIConfirmPassword = String.valueOf(tf_Accountmanagement_LaggTillKonto_ChangePassword.getPassword());
        
        sqlMethods = dataBase.returnDatabase();
        try {
            String sqlInsert = "Insert into person values (" + sqlMethods.getAutoIncrement("Person", "PersonID") + ",'" + GUIUsername + "','" + GUIName + "','" + GUIPassword + "')";

            if (GUIPassword.equals(GUIConfirmPassword)) {
                System.out.println("Password correct");
                   if (!doesPersonExistInDatabase(GUIUsername)) {
                       System.out.println("person doesn't exist");
                       sqlMethods.insert(sqlInsert);
                   }
                   else {
                       JOptionPane.showMessageDialog(null, "The username already exist");
                   }
            }
            else {
                JOptionPane.showMessageDialog(null, "The two passwords don't match each other");
            }
        }
        catch (InfException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_AccountManagement_LaggTillKonto_saveActionPerformed

    public boolean doesPersonExistInDatabase (String username) {
        String sql = "select username from person";
        ArrayList<String> A;
        boolean found = false;
        
        try {
            A = sqlMethods.fetchColumn(sql);
            
            for (String person : A) {
                if (person.equals(username)) {
                    found = true;
                }
            }
        }
        catch (InfException e) {
            System.out.println(e);
        }
        return found;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AndraKonto;
    private javax.swing.JPanel CardPanelHolder;
    private javax.swing.JPanel LaggTillKonto;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel TaBortKonto;
    private javax.swing.JButton btn_AccountManagement_LaggTillKonto_save;
    private javax.swing.JButton btn_AccountManagement_MainPanel_AndraKonto;
    private javax.swing.JButton btn_AccountManagement_MainPanel_Avsluta;
    private javax.swing.JButton btn_AccountManagement_MainPanel_LaggTillKonto;
    private javax.swing.JButton btn_AccountManagement_MainPanel_Loggaut;
    private javax.swing.JButton btn_AccountManagement_MainPanel_TaBortKonto;
    private javax.swing.JComboBox<String> cb_AccountManagement_MainPanel_AndraKonto_AccountChooser;
    private javax.swing.JComboBox<String> cb_AccountManagement_MainPanel_AndraKonto_AccountChooser1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPasswordField jPasswordField10;
    private javax.swing.JPasswordField jPasswordField5;
    private javax.swing.JPasswordField jPasswordField6;
    private javax.swing.JPasswordField jPasswordField9;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lbl_AccountManagement_LaggTillKonto_Password;
    private javax.swing.JLabel lbl_AccountManagement_LaggTillKonto_RepeatPassword;
    private javax.swing.JLabel lbl_AccountManagement_LaggTillKonto_name;
    private javax.swing.JLabel lbl_AccountManagement_LaggTillKonto_username;
    private javax.swing.JTextField tf_AccountManagement_LaggTillKonto_Name;
    private javax.swing.JPasswordField tf_AccountManagement_LaggTillKonto_Password;
    private javax.swing.JTextField tf_AccountManagement_LaggTillKonto_Username;
    private javax.swing.JPasswordField tf_Accountmanagement_LaggTillKonto_ChangePassword;
    // End of variables declaration//GEN-END:variables
}
