/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafiskinterface;

import java.util.*;
import java.awt.*;
import java.awt.CardLayout;
/**
 *
 * @author Simon
 */
public class Main extends javax.swing.JFrame {
    

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();   
        this.setLocationRelativeTo(null);
        CardLayout card = (CardLayout)pnl_Main_MainMiddleWindow.getLayout();
        card.show(pnl_Main_MainMiddleWindow, "card4");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Main_MainBackgroundPanel = new javax.swing.JPanel();
        pnl_Main_TopBorderMenu = new javax.swing.JPanel();
        btn_Main_SkapaMote = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btn_Main_Education = new javax.swing.JButton();
        btn_Main_Research = new javax.swing.JButton();
        btn_Main_Social = new javax.swing.JButton();
        pnl_Main_SidePanelMenu = new javax.swing.JPanel();
        pnl_Main_MainMiddleWindow = new javax.swing.JPanel();
        pnl_MainMiddleWindow_Utbildning = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnl_MainMiddleWindow_Forskning = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tpn_Main_MainMiddleWindow_Research_MainPane = new javax.swing.JTabbedPane();
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow = new javax.swing.JTextPane();
        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_CreatePost = new javax.swing.JButton();
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow1 = new javax.swing.JTextPane();
        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2_CreatePost = new javax.swing.JButton();
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow2 = new javax.swing.JTextPane();
        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3_CreatePost = new javax.swing.JButton();
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow3 = new javax.swing.JTextPane();
        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4_CreatePost = new javax.swing.JButton();
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow4 = new javax.swing.JTextPane();
        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5_CreatePost = new javax.swing.JButton();
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow5 = new javax.swing.JTextPane();
        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6_CreatePost = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        pnl_MainMiddleWindow_Social = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_Main_Avsluta = new javax.swing.JButton();
        btn_Main_Loggaut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1266, 668));
        setResizable(false);

        pnl_Main_MainBackgroundPanel.setBackground(new java.awt.Color(153, 153, 153));

        pnl_Main_TopBorderMenu.setBackground(new java.awt.Color(255, 255, 255));

        btn_Main_SkapaMote.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_Main_SkapaMote.setText("Skapa möte ");
        btn_Main_SkapaMote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Main_SkapaMoteActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton1.setText("Se möten");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_Main_Education.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_Main_Education.setText("Utbildning");
        btn_Main_Education.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Main_EducationActionPerformed(evt);
            }
        });

        btn_Main_Research.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_Main_Research.setText("Forskning");
        btn_Main_Research.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Main_ResearchActionPerformed(evt);
            }
        });

        btn_Main_Social.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_Main_Social.setText("Social");
        btn_Main_Social.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Main_SocialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_Main_TopBorderMenuLayout = new javax.swing.GroupLayout(pnl_Main_TopBorderMenu);
        pnl_Main_TopBorderMenu.setLayout(pnl_Main_TopBorderMenuLayout);
        pnl_Main_TopBorderMenuLayout.setHorizontalGroup(
            pnl_Main_TopBorderMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Main_TopBorderMenuLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btn_Main_Education, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn_Main_Research, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn_Main_Social, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btn_Main_SkapaMote)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_Main_TopBorderMenuLayout.setVerticalGroup(
            pnl_Main_TopBorderMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Main_TopBorderMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Main_TopBorderMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Main_Education, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Main_Social, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_Main_TopBorderMenuLayout.createSequentialGroup()
                        .addGroup(pnl_Main_TopBorderMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Main_SkapaMote, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btn_Main_Research, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnl_Main_TopBorderMenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_Main_SkapaMote, jButton1});

        pnl_Main_SidePanelMenu.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnl_Main_SidePanelMenuLayout = new javax.swing.GroupLayout(pnl_Main_SidePanelMenu);
        pnl_Main_SidePanelMenu.setLayout(pnl_Main_SidePanelMenuLayout);
        pnl_Main_SidePanelMenuLayout.setHorizontalGroup(
            pnl_Main_SidePanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );
        pnl_Main_SidePanelMenuLayout.setVerticalGroup(
            pnl_Main_SidePanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );

        pnl_Main_MainMiddleWindow.setBackground(new java.awt.Color(102, 102, 102));
        pnl_Main_MainMiddleWindow.setLayout(new java.awt.CardLayout());

        pnl_MainMiddleWindow_Utbildning.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel1.setText("Utbildning");

        javax.swing.GroupLayout pnl_MainMiddleWindow_UtbildningLayout = new javax.swing.GroupLayout(pnl_MainMiddleWindow_Utbildning);
        pnl_MainMiddleWindow_Utbildning.setLayout(pnl_MainMiddleWindow_UtbildningLayout);
        pnl_MainMiddleWindow_UtbildningLayout.setHorizontalGroup(
            pnl_MainMiddleWindow_UtbildningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_MainMiddleWindow_UtbildningLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addContainerGap(676, Short.MAX_VALUE))
        );
        pnl_MainMiddleWindow_UtbildningLayout.setVerticalGroup(
            pnl_MainMiddleWindow_UtbildningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_MainMiddleWindow_UtbildningLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addContainerGap(366, Short.MAX_VALUE))
        );

        pnl_Main_MainMiddleWindow.add(pnl_MainMiddleWindow_Utbildning, "card2");

        pnl_MainMiddleWindow_Forskning.setBackground(new java.awt.Color(153, 153, 255));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel2.setText("Forskning");

        tpn_Main_MainMiddleWindow_Research_MainPane.setPreferredSize(new java.awt.Dimension(529, 100));

        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1.setMinimumSize(new java.awt.Dimension(529, 100));
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1.setPreferredSize(new java.awt.Dimension(529, 393));

        jScrollPane2.setViewportView(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow);

        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_CreatePost.setText("Nytt inlägg");
        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_CreatePost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_CreatePostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1Layout = new javax.swing.GroupLayout(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1.setLayout(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1Layout);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1Layout.setHorizontalGroup(
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1Layout.createSequentialGroup()
                        .addGap(0, 419, Short.MAX_VALUE)
                        .addComponent(btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_CreatePost))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1Layout.setVerticalGroup(
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_CreatePost)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        tpn_Main_MainMiddleWindow_Research_MainPane.addTab("Forskargrupp 1", tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1);

        jScrollPane3.setViewportView(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow1);

        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2_CreatePost.setText("Nytt inlägg");
        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2_CreatePost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2_CreatePostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2Layout = new javax.swing.GroupLayout(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2.setLayout(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2Layout);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2Layout.setHorizontalGroup(
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2Layout.createSequentialGroup()
                        .addGap(0, 419, Short.MAX_VALUE)
                        .addComponent(btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2_CreatePost))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2Layout.setVerticalGroup(
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2_CreatePost)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        tpn_Main_MainMiddleWindow_Research_MainPane.addTab("Forskargrupp 2", tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2);

        jScrollPane4.setViewportView(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow2);

        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3_CreatePost.setText("Nytt inlägg");
        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3_CreatePost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3_CreatePostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3Layout = new javax.swing.GroupLayout(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3.setLayout(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3Layout);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3Layout.setHorizontalGroup(
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3Layout.createSequentialGroup()
                        .addGap(0, 419, Short.MAX_VALUE)
                        .addComponent(btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3_CreatePost))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3Layout.setVerticalGroup(
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3_CreatePost)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        tpn_Main_MainMiddleWindow_Research_MainPane.addTab("Forskargrupp 3", tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3);

        jScrollPane5.setViewportView(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow3);

        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4_CreatePost.setText("Nytt inlägg");
        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4_CreatePost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4_CreatePostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4Layout = new javax.swing.GroupLayout(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4.setLayout(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4Layout);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4Layout.setHorizontalGroup(
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4Layout.createSequentialGroup()
                        .addGap(0, 419, Short.MAX_VALUE)
                        .addComponent(btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4_CreatePost))
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4Layout.setVerticalGroup(
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4_CreatePost)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        tpn_Main_MainMiddleWindow_Research_MainPane.addTab("Forskargrupp 4", tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4);

        jScrollPane6.setViewportView(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow4);

        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5_CreatePost.setText("Nytt inlägg");
        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5_CreatePost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5_CreatePostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5Layout = new javax.swing.GroupLayout(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5.setLayout(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5Layout);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5Layout.setHorizontalGroup(
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5Layout.createSequentialGroup()
                        .addGap(0, 419, Short.MAX_VALUE)
                        .addComponent(btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5_CreatePost))
                    .addComponent(jScrollPane6))
                .addContainerGap())
        );
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5Layout.setVerticalGroup(
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5_CreatePost)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        tpn_Main_MainMiddleWindow_Research_MainPane.addTab("Forskargrupp 5", tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5);

        jScrollPane7.setViewportView(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow5);

        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6_CreatePost.setText("Nytt inlägg");
        btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6_CreatePost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6_CreatePostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6Layout = new javax.swing.GroupLayout(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6.setLayout(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6Layout);
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6Layout.setHorizontalGroup(
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6Layout.createSequentialGroup()
                        .addGap(0, 419, Short.MAX_VALUE)
                        .addComponent(btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6_CreatePost))
                    .addComponent(jScrollPane7))
                .addContainerGap())
        );
        tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6Layout.setVerticalGroup(
            tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6_CreatePost)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        tpn_Main_MainMiddleWindow_Research_MainPane.addTab("Forskargrupp 6", tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6);

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Nyheter");

        javax.swing.GroupLayout pnl_MainMiddleWindow_ForskningLayout = new javax.swing.GroupLayout(pnl_MainMiddleWindow_Forskning);
        pnl_MainMiddleWindow_Forskning.setLayout(pnl_MainMiddleWindow_ForskningLayout);
        pnl_MainMiddleWindow_ForskningLayout.setHorizontalGroup(
            pnl_MainMiddleWindow_ForskningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_MainMiddleWindow_ForskningLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(pnl_MainMiddleWindow_ForskningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tpn_Main_MainMiddleWindow_Research_MainPane, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(pnl_MainMiddleWindow_ForskningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_MainMiddleWindow_ForskningLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_MainMiddleWindow_ForskningLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(116, 116, 116))))
        );
        pnl_MainMiddleWindow_ForskningLayout.setVerticalGroup(
            pnl_MainMiddleWindow_ForskningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_MainMiddleWindow_ForskningLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_MainMiddleWindow_ForskningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_MainMiddleWindow_ForskningLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tpn_Main_MainMiddleWindow_Research_MainPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnl_MainMiddleWindow_ForskningLayout.createSequentialGroup()
                        .addGap(0, 37, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pnl_Main_MainMiddleWindow.add(pnl_MainMiddleWindow_Forskning, "card3");

        pnl_MainMiddleWindow_Social.setBackground(new java.awt.Color(204, 204, 255));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel3.setText("Social");

        javax.swing.GroupLayout pnl_MainMiddleWindow_SocialLayout = new javax.swing.GroupLayout(pnl_MainMiddleWindow_Social);
        pnl_MainMiddleWindow_Social.setLayout(pnl_MainMiddleWindow_SocialLayout);
        pnl_MainMiddleWindow_SocialLayout.setHorizontalGroup(
            pnl_MainMiddleWindow_SocialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_MainMiddleWindow_SocialLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel3)
                .addContainerGap(744, Short.MAX_VALUE))
        );
        pnl_MainMiddleWindow_SocialLayout.setVerticalGroup(
            pnl_MainMiddleWindow_SocialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_MainMiddleWindow_SocialLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel3)
                .addContainerGap(366, Short.MAX_VALUE))
        );

        pnl_Main_MainMiddleWindow.add(pnl_MainMiddleWindow_Social, "card4");

        btn_Main_Avsluta.setText("Avsluta");
        btn_Main_Avsluta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Main_AvslutaActionPerformed(evt);
            }
        });

        btn_Main_Loggaut.setText("Logga ut");
        btn_Main_Loggaut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Main_LoggautActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_Main_MainBackgroundPanelLayout = new javax.swing.GroupLayout(pnl_Main_MainBackgroundPanel);
        pnl_Main_MainBackgroundPanel.setLayout(pnl_Main_MainBackgroundPanelLayout);
        pnl_Main_MainBackgroundPanelLayout.setHorizontalGroup(
            pnl_Main_MainBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Main_TopBorderMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl_Main_MainBackgroundPanelLayout.createSequentialGroup()
                .addGroup(pnl_Main_MainBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_Main_MainBackgroundPanelLayout.createSequentialGroup()
                        .addContainerGap(53, Short.MAX_VALUE)
                        .addComponent(pnl_Main_MainMiddleWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addGroup(pnl_Main_MainBackgroundPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_Main_Avsluta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Main_Loggaut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(pnl_Main_SidePanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_Main_MainBackgroundPanelLayout.setVerticalGroup(
            pnl_Main_MainBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Main_MainBackgroundPanelLayout.createSequentialGroup()
                .addComponent(pnl_Main_TopBorderMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnl_Main_MainBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_Main_MainBackgroundPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnl_Main_SidePanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_Main_MainBackgroundPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(pnl_Main_MainMiddleWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_Main_MainBackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Main_Avsluta)
                            .addComponent(btn_Main_Loggaut))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Main_MainBackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Main_MainBackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private void btn_Main_AvslutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Main_AvslutaActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btn_Main_AvslutaActionPerformed

    private void btn_Main_SkapaMoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Main_SkapaMoteActionPerformed
         GrafikHelper.InitieraSkapaMote();
    }//GEN-LAST:event_btn_Main_SkapaMoteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         GrafikHelper.InitieraSeMoten();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_Main_EducationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Main_EducationActionPerformed
        CardLayout card = (CardLayout)pnl_Main_MainMiddleWindow.getLayout();
        card.show(pnl_Main_MainMiddleWindow, "card2"); 
    }//GEN-LAST:event_btn_Main_EducationActionPerformed

    private void btn_Main_ResearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Main_ResearchActionPerformed
        CardLayout card = (CardLayout)pnl_Main_MainMiddleWindow.getLayout();
        card.show(pnl_Main_MainMiddleWindow, "card3"); 
    }//GEN-LAST:event_btn_Main_ResearchActionPerformed

    private void btn_Main_SocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Main_SocialActionPerformed
        CardLayout card = (CardLayout)pnl_Main_MainMiddleWindow.getLayout();
        card.show(pnl_Main_MainMiddleWindow, "card4"); 
    }//GEN-LAST:event_btn_Main_SocialActionPerformed

    private void btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_CreatePostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_CreatePostActionPerformed
        GrafikHelper.InitieraCreateNewPost("rGroup1");
    }//GEN-LAST:event_btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_CreatePostActionPerformed

    private void btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2_CreatePostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2_CreatePostActionPerformed
        GrafikHelper.InitieraCreateNewPost("rGroup2");
    }//GEN-LAST:event_btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2_CreatePostActionPerformed

    private void btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3_CreatePostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3_CreatePostActionPerformed
        GrafikHelper.InitieraCreateNewPost("rGroup3");
    }//GEN-LAST:event_btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3_CreatePostActionPerformed

    private void btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4_CreatePostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4_CreatePostActionPerformed
        GrafikHelper.InitieraCreateNewPost("rGroup4");
    }//GEN-LAST:event_btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4_CreatePostActionPerformed

    private void btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5_CreatePostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5_CreatePostActionPerformed
        GrafikHelper.InitieraCreateNewPost("rGroup5");
    }//GEN-LAST:event_btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5_CreatePostActionPerformed

    private void btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6_CreatePostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6_CreatePostActionPerformed
        GrafikHelper.InitieraCreateNewPost("rGroup6");
    }//GEN-LAST:event_btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6_CreatePostActionPerformed

    private void btn_Main_LoggautActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Main_LoggautActionPerformed
        GrafikHelper.DisposeFrame();
        GrafikHelper.InitieraLogIn();
    }//GEN-LAST:event_btn_Main_LoggautActionPerformed

  
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Main_Avsluta;
    private javax.swing.JButton btn_Main_Education;
    private javax.swing.JButton btn_Main_Loggaut;
    private javax.swing.JButton btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_CreatePost;
    private javax.swing.JButton btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2_CreatePost;
    private javax.swing.JButton btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3_CreatePost;
    private javax.swing.JButton btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4_CreatePost;
    private javax.swing.JButton btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5_CreatePost;
    private javax.swing.JButton btn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6_CreatePost;
    private javax.swing.JButton btn_Main_Research;
    private javax.swing.JButton btn_Main_SkapaMote;
    private javax.swing.JButton btn_Main_Social;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel pnl_MainMiddleWindow_Forskning;
    private javax.swing.JPanel pnl_MainMiddleWindow_Social;
    private javax.swing.JPanel pnl_MainMiddleWindow_Utbildning;
    private javax.swing.JPanel pnl_Main_MainBackgroundPanel;
    private javax.swing.JPanel pnl_Main_MainMiddleWindow;
    private javax.swing.JPanel pnl_Main_SidePanelMenu;
    private javax.swing.JPanel pnl_Main_TopBorderMenu;
    private javax.swing.JTabbedPane tpn_Main_MainMiddleWindow_Research_MainPane;
    private javax.swing.JPanel tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1;
    private javax.swing.JTextPane tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow;
    private javax.swing.JTextPane tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow1;
    private javax.swing.JTextPane tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow2;
    private javax.swing.JTextPane tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow3;
    private javax.swing.JTextPane tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow4;
    private javax.swing.JTextPane tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup1_ForumWindow5;
    private javax.swing.JPanel tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup2;
    private javax.swing.JPanel tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup3;
    private javax.swing.JPanel tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup4;
    private javax.swing.JPanel tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup5;
    private javax.swing.JPanel tpn_Main_MainMiddleWindow_Research_MainPane_ResearchGroup6;
    // End of variables declaration//GEN-END:variables
}
